### ISSUE TITLE
uwsgi-plugin-python37u

### ISSUE THREAD

**Issue by sampowers** [iusrepo/wishlist#203]
### What new package do you want?

uwsgi-plugin-python37u 2.0.17

### Why?

We'd like to run our uwsgi application on python 3.7, and the uwsgi plugin is a requirement for that.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by sampowers** [comment]
Presumably this would depend on https://github.com/iuscommunity/wishlist/issues/200

**Comment by carlwgeorge** [comment]
Closing this for the same reasons as #200.  New python versions (and their related packages) should be added to EPEL instead of IUS.
