### ISSUE TITLE
poppler-utils-0.67.0 or latest (CentOS provides 0.26.5)

### ISSUE THREAD

**Issue by speckins** [iusrepo/wishlist#205]
### What new package do you want?

poppler-utils-0.67.0

### Why?

I'm really only interested in the `pdfunite` utility.  The version of poppler-utils in the CentOS 7 official repositories is 0.26.5, which is from Sept 2014.  There have been a lot of [bug fixes](https://poppler.freedesktop.org/releases.html) over the past four years.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

Yep, we'll be using this in production.

**Comment by carlwgeorge** [comment]
What specific issues do you want to see fixed?  Have you opened bugzilla's with Red Hat to see if backporting is possible?  Even better, depending on ABI compatibility they may be able to just update the base package outright.  Red Hat has been much more open to that in the last few years.

**Comment by speckins** [comment]
I'll close this.  There was no specific issue.  We've had so many problems with other ancient CentOS packages that I was sure this was going to be a problem, too, given how far behind it is.  However, we've been using it in production for a few months now and have experienced no problems (that aren't also in the latest version).

(Also:  thanks for your work on other packages like git and httpd; we appreciate it!)
