### ISSUE TITLE
ImageMagick 7.0.8-10 (and php72-pecl-imagick compiled against that)

### ISSUE THREAD

**Issue by wiza** [iusrepo/wishlist#206]
### What new package do you want?

ImageMagick 7.0.8-10 (and php-pecl-imagick compiled against that)

### Why?

ImageMagick 7.0.4-7 added possibility to whitelist for example just web-safe image types.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
We normally fork our spec files from Fedora, but even Rawhide doesn't have ImageMagick 7 yet.

https://bugzilla.redhat.com/show_bug.cgi?id=1672665

Even when they do, I'm hesitant to proceed with this.  IUS typically builds against stock libraries whenever possible.  For as long as the imagick PECL module works with the stock ImageMagick version, I'd rather keep it using that.  If someone else does the work to add a parallel ImageMagick 7 to EPEL, I would consider using it, as it wouldn't add any maintenance overhead to IUS.

**Comment by carlwgeorge** [comment]
Just found another Fedora bugzilla related to ImageMagick 7.

https://bugzilla.redhat.com/show_bug.cgi?id=1490080#c59

> The 'ImageMagick' package will likely never be upgraded to 7.x. A new 'ImageMagick7' package should be introduced into Fedora if anyone wants version 7. Version 7 is wildly incompatible with old software.

Once ImageMagick7 is added to Fedora, it can be branched for EPEL.  I don't have the bandwidth to take that on myself, but if someone else makes it happen I'll be happy to investigate building IUS packages against it.
