### ISSUE TITLE
php72u-pecl-amqp

### ISSUE THREAD

**Issue by talawahtech** [iusrepo/wishlist#208]
### What new package do you want?

php72u-pecl-amqp

### Why?

I'm updating from php70u to php72u. and my application depends on amqp, but there is no php72u-pecl-amqp package in the repo.

OS: CentOS 7

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by martinnix** [comment]
I am in a similar position  - stuck at php71 (which is in security eol) - please advise!

**Comment by milosz** [comment]
Is there any news? How can we help to make this happen?

**Comment by milosz** [comment]
I have managed to build amqp module for php72u using https://github.com/iuscommunity-pkg/php71u-pecl-amqp repository for testing purpose, I will probably play with it next week.

Modified line:
{code}
%global php         php72u
{code}

Build process:
{code}
yum groupinstall 'Development Tools'
spectool -g -R SPECS/php71u-pecl-amqp.spec 
rpmbuild -ba SPECS/php71u-pecl-amqp.spec
{code}

**Comment by carlwgeorge** [comment]
Sorry for the delays here.  I've created [php72u-pecl-amqp](https://github.com/iusrepo/php72u-pecl-amqp).  It's available from ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14#issuecomment-488866147).  You should be able to install it by following these steps.

```
yum --enablerepo ius-testing update ius-release
yum clean all
yum install php72u-pecl-amqp
```

Please try it out and share your feedback.

**Comment by milosz** [comment]
Thanks, U have installed `yum install https://repo.ius.io/testing/7/x86_64/packages/p/php72u-pecl-amqp-1.9.4-3.el7.ius.x86_64.rpm` and it looks fine, app is connecting to RabbitMQ server and I have not encountered any problems.

**Comment by carlwgeorge** [comment]
Thanks for the feedback @milosz.  I've promoted php72u-pecl-amqp to the stable repo.  Enjoy!
