### ISSUE TITLE
php72u-pecl-apcu-bc

### ISSUE THREAD

**Issue by wiza** [iusrepo/wishlist#216]
### What new package do you want?

APCu backwards compatibility module for PHP 7.2

### Why?

APCu backwards compatibility module is still widely used in projects to close the feature cap when moved from APC to opcache without rewriting everything.

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
We've created a [php72u-pecl-apcu-bc](https://github.com/iusrepo/php72u-pecl-apcu-bc) package.  It is available from ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).  Please try it out and share your feedback.

**Comment by carlwgeorge** [comment]
@wiza How is this package working for you?

**Comment by wiza** [comment]
We wrote it out in the past half a year so no need for it anymore. Sorry for forgotting to close this before.

**Comment by carlwgeorge** [comment]
Due to lack of feedback, I have removed php72u-pecl-apcu-bc from the testing repo.  The spec file is available [here](https://github.com/iusrepo/php72u-pecl-apcu-bc), and the RPMs that were built are available [here](https://cirrus-ci.com/task/5161331582304256).  We can revive this in the future if there are people willing to test and provide feedback.

**Comment by jasondpereira** [comment]
@carlwgeorge Can you add php72u-pecl-apcu-bc back to the repo.

**Comment by carlwgeorge** [comment]
@jasondpereira Are you willing to test it and provide feedback?  If so I can republish it to the testing repo and then later to the main repo.

**Comment by jasondpereira** [comment]
@carlwgeorge I will have our QA team do some smoke testing and let you know if we see any issues.

**Comment by carlwgeorge** [comment]
I've re-added php72u-pecl-apcu-bc-1.0.5-2.el7 to the testing repos.  Let me know if it works for you.

**Comment by jasondpereira** [comment]
@carlwgeorge  can you also add php72u-pecl-apc to the testing repos I can provide testing feed back.

**Comment by jasondpereira** [comment]
@carlwgeorge  our QA team said  php72u-pecl-apcu-bc passed all tests. Can you move this to the release branch?

**Comment by carlwgeorge** [comment]
This has been pushed to stable.  Enjoy!
