### ISSUE TITLE
php72u-pecl-lzf

### ISSUE THREAD

**Issue by cmacdonald-au** [iusrepo/wishlist#223]
### What new package do you want?

php72u-pecl-lzf

### Why?

To allow an upgrade path php7[01]u -> php72u for projects that depend on pecl-lzf functionality currently provided by php70u-pecl-lfz (#165) && php71u-pecl-lzf (#172)

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

Thanks!

**Comment by carlwgeorge** [comment]
We've created [php72u-pecl-lzf](https://github.com/iusrepo/php72u-pecl-lzf).  It is available from ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).  Please try it out and share your feedback.

**Comment by carlwgeorge** [comment]
@cmacdonald-au How is this package working for you?

**Comment by cmacdonald-au** [comment]
Thanks for the nudge - testing is in progress.

**Comment by cmacdonald-au** [comment]
STABLE

Thanks for this!

**Comment by carlwgeorge** [comment]
Thanks for sharing your feedback.  This package has been promoted from the testing repository to the main repository.
