### ISSUE TITLE
haproxy20

### ISSUE THREAD

**Issue by thehaven** [iusrepo/wishlist#224]
### What new package do you want?

haproxy19u-1.9.1-1.ius.el7.centos.x86_64

### Why?

HAProxy 1.9.x is the latest stable release branch for HAProxy see the changelog and release announcements below:
http://www.haproxy.org/download/1.9/src/CHANGELOG
https://www.haproxy.com/blog/haproxy-1-9-has-arrived/

For major features; To quote the devs:

> HAProxy Technologies is proud to announce the release of HAProxy 1.9. This release brings a native HTTP representation (HTX) powering end-to-end HTTP/2 support and paving the way for future innovations such as HTTP/3 (QUIC). It also contains improvements to buffers and connection management including connection pooling to backends, threading optimizations, updates to the Runtime API, and much more.

I have a spec build in testing currently based off IUS haproxy18u and so far have not hit any issues (early days though):
https://github.com/thehaven/haproxy19u

### Testing
I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by phateuk** [comment]
+1 HaProxy 1.9 is upto 1.9.4 now. Please please can someone add this to IUS :D:D

**Comment by carlwgeorge** [comment]
IUS typically forks our spec files from Fedora.  Fedora has not yet switched to the 1.9 branch.  I'm going to hold off on creating haproxy19 in IUS until that happens to reduce the number of spec file changes I need to make.

**Comment by Ryuzavi** [comment]
Hi.  Is there a way to raise an issue with Fedora?  HAProxy now is already on 1.9.6 now.  Cheers!

**Comment by carlwgeorge** [comment]
Fedora has chosen to skip the 1.9 branch ([rhbz#1670264](https://bugzilla.redhat.com/show_bug.cgi?id=1670264)).  The Fedora maintainer pointed out an interesting note on https://www.haproxy.org regarding 1.9:

> An important point to note, this technical release is not suitable for inclusion in distros, as it will only be maintained for approximately one year (till 2.1 is out). Version 2.0 coming in May will be long-lived and more suitable for distros.

IUS could still package this, as we have no qualms about dropping packages at the upstream EOL date.

**Comment by DeesoSaeed** [comment]
Haproxy 2.0 is out and it's a LTS branch. It would be nice to have the packages once we are at a "safe" patch level (2.0.3 or so...) Maybe after summer.

**Comment by carlwgeorge** [comment]
I agree, I think at this point it makes sense to follow the upstream recommendation and just create haproxy20.  I'll explore this once Fedora Rawhide updates to 2.0.x.

**Comment by carlwgeorge** [comment]
I've sent a [pull request](https://src.fedoraproject.org/rpms/haproxy/pull-request/6) to Fedora to update Rawhide to 2.0.

**Comment by dseira** [comment]
Any update on this?

**Comment by dseira** [comment]
Thanks! I will deploy it in our lab and provide you some feedback.

**Comment by dseira** [comment]
With [these options](https://github.com/iusrepo/haproxy20/blob/2.0.5-2/haproxy.cfg#L38-L40) there are the following errors:

```
[ALERT] 239/200530 (56345) : Proxy 'https-fe': unable to set SSL cipher list to 'PROFILE=SYSTEM' for bind ':443' at [/etc/haproxy/haproxy.cfg:85].
[ALERT] 239/200530 (56345) : Proxy 'https-fe': unable to set SSL cipher list to 'PROFILE=SYSTEM' for bind ':443' at [/etc/haproxy/haproxy.cfg:85].
[ALERT] 240/200530 (56345) : Fatal errors found in configuration.
```

The OS used is:

```
CentOS Linux release 7.6.1810 (Core)
```

**Comment by carlwgeorge** [comment]
That's what I was afraid of.  [This](https://github.com/iusrepo/haproxy20/commit/2b272c68647d7cf56ad4da2fabc2dbdafa4b9346) should take care of it, try out the latest haproxy20-2.0.5-3 build.

**Comment by dseira** [comment]
Done, latest version is installed. I will keep the workload tests running for the next days.

BTW, why is the name of the package changed? previous versions include the `u` character (`haproxy18u`).

**Comment by carlwgeorge** [comment]
We used a `u` suffix in the past to avoid conflicts with RHSCL.  However, that was only a problem with early collections.  After the early ones they started added a `rh-` prefix.  The `u` just isn't necessary anymore.

Speaking of software collections, I noticed that the rh-haproxy18 collection still has those problematic cipher settings.  The service starts out of the box on CentOS 7.6, but I haven't configured anything extra like you have. Would you mind trying out that package to compare and see if you get the same error?

**Comment by dseira** [comment]
Tested the rh-haproxy18.

With the packaged haproxy.cfg it doesn't show any error; the service starts correctly. But if you have some frontend bind to 443 the error is still there:

```
/opt/rh/rh-haproxy18/root/usr/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg
[ALERT] 240/171347 (17777) : Proxy 'https-fe': unable to set SSL cipher list to 'PROFILE=SYSTEM' for bind ':443' at [/etc/haproxy/haproxy.cfg:85].
[ALERT] 240/171347 (17777) : Proxy 'https-fe': unable to set SSL cipher list to 'PROFILE=SYSTEM' for bind ':443' at [/etc/haproxy/haproxy.cfg:85].
[ALERT] 240/171347 (17777) : Fatal errors found in configuration.
```

**Comment by carlwgeorge** [comment]
Thanks for that confirmation.  I would say that's a bug and someone should probably tell Red Hat about that.  Someone that cares about RHSCL (not me). :grin:

**Comment by dseira** [comment]
Indeed XD

I will continue to testing haproxy20.

**Comment by carlwgeorge** [comment]
Sure thing, when you feel comfortable with it just say so and I'll publish it to the main repo.

**Comment by dseira** [comment]
It's being around almost a week since I'm making tests in the haproxy 2 without any issue. I think we can publish it to the main repo.

**Comment by carlwgeorge** [comment]
Done.  Enjoy!

**Comment by dseira** [comment]
Any date from when it will be available in main repo?

**Comment by carlwgeorge** [comment]
I moved it to the main repo when I made my last comment.

```
# repoquery --info haproxy20

Name        : haproxy20
Version     : 2.0.5
Release     : 3.el7.ius
Architecture: x86_64
Size        : 5041656
Packager    : None
Group       : Unspecified
URL         : http://www.haproxy.org/
Repository  : ius
Summary     : HAProxy reverse proxy for high availability environments
Source      : haproxy20-2.0.5-3.el7.ius.src.rpm
Description :
HAProxy is a TCP/HTTP reverse proxy which is particularly suited for high
availability environments. Indeed, it can:
 - route HTTP requests depending on statically assigned cookies
 - spread load among several servers while assuring server persistence
   through the use of HTTP cookies
 - switch to backup servers in the event a main one fails
 - accept connections to special ports dedicated to service monitoring
 - stop accepting connections without breaking existing ones
 - add, modify, and delete HTTP headers in both directions
 - block requests matching particular patterns
 - report detailed status to authenticated users from a URI
   intercepted from the application
```

**Comment by dseira** [comment]
Ok. I didn't see it on https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/repoview/letter_h.group.html (from https://ius.io/Packages/) and I thought about the release cycle.

Thanks!

**Comment by carlwgeorge** [comment]
Yeah, the website [needs some work](https://github.com/iusrepo/ius.io/issues/40), sorry for the confusion.

**Comment by mbaranczak** [comment]
Hello. Sorry to resurrect an old thread, but this is the only information I could find about my problem.

I'm trying to set up HAProxy 2.2.17 on Amazon Linux. I need it to point to a backend that uses HTTPS. I'm getting the same error mentioned above: "unable to set SSL cipher list to 'PROFILE=SYSTEM'". Can somebody explain what the error means? When I comment out these lines under "global", the error goes away:

ssl-default-bind-ciphers PROFILE=SYSTEM
ssl-default-server-ciphers PROFILE=SYSTEM

I'm guessing that without these lines, it uses the compiled-in default settings, and that these defaults are fine for most normal users. Is that guess correct?

**Comment by carlwgeorge** [comment]
@mbaranczak Cipher profiles is something that Fedora and RHEL8/9 add to their openssl to allow a common set of ciphers to be applied system-wide.  IUS packages are based on Fedora packages, but adapted to work on RHEL7.  RHEL7 lacks support for that feature, so IUS packages remove those lines of the config file.  It sounds like Amazon Linux doesn't have that feature either, but you'd have to confirm that with AWS.  You're correct that without those lines it defaults to use compiled in defaults.  It's up to you to determine if those defaults work for you.  That's all I know about it so if you have further questions I suggest [contacting the upstream](https://www.haproxy.org/#tact).
