### ISSUE TITLE
keepalived2

### ISSUE THREAD

**Issue by brokenjacobs** [iusrepo/wishlist#234]
### What new package do you want?
keepalived 2.0.X

### Why?
keepalived 2.0 has support for file based status checks which are less resource intensive and fragile than the script based process checks in the 1.X release train.

This package is currently available in fedora 29/30 if that helps at all

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
With some help from @evitalis, we've created a [keepalived2](https://github.com/iusrepo/keepalived2) package.  It is available from ius-testing on the new [IUS CDN](https://github.com/iusrepo/infrastructure/issues/14).  Please try it out and share your feedback.

**Comment by carlwgeorge** [comment]
@brokenjacobs How is this package working for you?

**Comment by brokenjacobs** [comment]
we haven't had a chance to try it out but should be using it within the next month. Thanks for getting this in!

**Comment by carlwgeorge** [comment]
Any word on testing @brokenjacobs?

**Comment by carlwgeorge** [comment]
@brokenjacobs Still waiting on feedback for this package.  If you don't reply soon I'm going to remove the package from the testing repo and close this issue.

**Comment by carlwgeorge** [comment]
Due to lack of feedback, I have removed keepalived2 from the testing repo.  The spec file is available [here](https://github.com/iusrepo/keepalived2), and the RPMs that were built are available [here](https://cirrus-ci.com/task/5705717713993728).  We can revive this in the future if there are people willing to test and provide feedback.
