### ISSUE TITLE
php73-pecl-memcached

### ISSUE THREAD

**Issue by ppascher** [iusrepo/wishlist#236]
### What new package do you want?

php73-pecl-memcached

### Why?

I need it for my nextcloud setup. Stable release supporting PHP 7.3 seems to be available at
https://github.com/php-memcached-dev/php-memcached/releases

### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
I've created [php73-pecl-memcached](https://github.com/iusrepo/php73-pecl-memcached) and published it to ius-testing.  Please try it out and share your feedback here.

**Comment by futureweb** [comment]
@carlwgeorge - just installed it on our Testing Server (CentOS Linux release 7.6.1810 (Core)) - getting some WARNINGS on install with DNF - but Package itself seems to work ... 

> [root@localhost ~]# dnf install php73-pecl-memcached --enablerepo=ius-testing      
> Last metadata expiration check: 0:00:07 ago on Wed 12 Jun 2019 10:17:29 AM CEST.
> Dependencies resolved.
> ================================================================================================================================================================================================================================================================
>  Package                                                              Arch                                                   Version                                                          Repository                                                   Size
> ================================================================================================================================================================================================================================================================
> Installing:
>  php73-pecl-memcached                                                 x86_64                                                 3.1.3-3.el7.ius                                                  ius-testing                                                  68 k
> Installing dependencies:
>  php73-pecl-igbinary                                                  x86_64                                                 3.0.1-1.el7.ius                                                  ius                                                          86 k
>  php73-pecl-msgpack                                                   x86_64                                                 2.0.3-3.el7.ius                                                  ius-testing                                                  41 k
> 
> Transaction Summary
> ================================================================================================================================================================================================================================================================
> Install  3 Packages
> 
> Total download size: 194 k
> Installed size: 514 k
> Is this ok [y/N]: y
> Downloading Packages:
> (1/3): php73-pecl-msgpack-2.0.3-3.el7.ius.x86_64.rpm                                                                                                                                                                             61 kB/s |  41 kB     00:00    
> (2/3): php73-pecl-memcached-3.1.3-3.el7.ius.x86_64.rpm                                                                                                                                                                           98 kB/s |  68 kB     00:00    
> (3/3): php73-pecl-igbinary-3.0.1-1.el7.ius.x86_64.rpm                                                                                                                                                                           121 kB/s |  86 kB     00:00    
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
> Total                                                                                                                                                                                                                           274 kB/s | 194 kB     00:00     
> Running transaction check
> Transaction check succeeded.
> Running transaction test
> Transaction test succeeded.
> Running transaction
>   Preparing        :                                                                                                                                                                                                                                        1/1 
>   Installing       : php73-pecl-msgpack-2.0.3-3.el7.ius.x86_64                                                                                                                                                                                              1/3 
>   Installing       : php73-pecl-igbinary-3.0.1-1.el7.ius.x86_64                                                                                                                                                                                             2/3 
>   Installing       : php73-pecl-memcached-3.1.3-3.el7.ius.x86_64                                                                                                                                                                                            3/3 
>   Running scriptlet: php73-pecl-msgpack-2.0.3-3.el7.ius.x86_64                                                                                                                                                                                              3/3 
> PHP Warning:  PHP Startup: xxhash: Unable to initialize module
> Module compiled with module API=20170718
> PHP    compiled with module API=20180731
> These options need to match
>  in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library 'meminfo.so' (tried: /usr/lib64/php/modules/meminfo.so (/usr/lib64/php/modules/meminfo.so: undefined symbol: _zend_hash_add_new), /usr/lib64/php/modules/meminfo.so.so (/usr/lib64/php/modules/meminfo.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/pear/PEAR/PackageFile/v2/Validator.php on line 1933
> 
>   Running scriptlet: php73-pecl-igbinary-3.0.1-1.el7.ius.x86_64                                                                                                                                                                                             3/3 
> PHP Warning:  PHP Startup: xxhash: Unable to initialize module
> Module compiled with module API=20170718
> PHP    compiled with module API=20180731
> These options need to match
>  in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library 'meminfo.so' (tried: /usr/lib64/php/modules/meminfo.so (/usr/lib64/php/modules/meminfo.so: undefined symbol: _zend_hash_add_new), /usr/lib64/php/modules/meminfo.so.so (/usr/lib64/php/modules/meminfo.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/pear/PEAR/PackageFile/v2/Validator.php on line 1933
> 
>   Running scriptlet: php73-pecl-memcached-3.1.3-3.el7.ius.x86_64                                                                                                                                                                                            3/3 
> PHP Warning:  PHP Startup: xxhash: Unable to initialize module
> Module compiled with module API=20170718
> PHP    compiled with module API=20180731
> These options need to match
>  in Unknown on line 0
> PHP Warning:  PHP Startup: Unable to load dynamic library 'meminfo.so' (tried: /usr/lib64/php/modules/meminfo.so (/usr/lib64/php/modules/meminfo.so: undefined symbol: _zend_hash_add_new), /usr/lib64/php/modules/meminfo.so.so (/usr/lib64/php/modules/meminfo.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/share/pear/PEAR/PackageFile/v2/Validator.php on line 1933
> 
>   Verifying        : php73-pecl-igbinary-3.0.1-1.el7.ius.x86_64                                                                                                                                                                                             1/3 
>   Verifying        : php73-pecl-memcached-3.1.3-3.el7.ius.x86_64                                                                                                                                                                                            2/3 
>   Verifying        : php73-pecl-msgpack-2.0.3-3.el7.ius.x86_64                                                                                                                                                                                              3/3 
> 
> Installed:
>   php73-pecl-memcached-3.1.3-3.el7.ius.x86_64                                           php73-pecl-igbinary-3.0.1-1.el7.ius.x86_64                                           php73-pecl-msgpack-2.0.3-3.el7.ius.x86_64                                          
> 
> Complete!

**Comment by carlwgeorge** [comment]
Thanks for the confirmation.  I've promoted this to the stable repo.  Enjoy!

**Comment by ppascher** [comment]
Trying to install php73-memcached I get an error for dependency php73-pecl-msgpack which does not seem to be available yet in stable.
```--> Processing Dependency: php73-pecl-msgpack(x86-64) for package: php73-pecl-memcached-3.1.3-3.el7.ius.x86_64
--> Finished Dependency Resolution
Error: Package: php73-pecl-memcached-3.1.3-3.el7.ius.x86_64 (katello_ius)
           Requires: php73-pecl-msgpack(x86-64)```

**Comment by carlwgeorge** [comment]
Right you are, I forgot to promote php73-pecl-msgpack at the same time.  It's fixed now.  Thanks for pointing that out so I could get it sorted out.
