### ISSUE TITLE
php73-pecl-yaml

### ISSUE THREAD

**Issue by fregster** [iusrepo/wishlist#239]
YAML Libary for PHP 7.3

### Why?

YAML is a common configuration file for many popular projects. With out YAML support the IUS PHP 7.3 package has limited use for many applications I use and write. Please can we include it.

Currently available as php71u-pecl-yaml and php72u-pecl-yaml

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by rocket8899** [comment]
I am available at any time for the next few weeks

**Comment by carlwgeorge** [comment]
[php73-pecl-yaml](https://github.com/iusrepo/php73-pecl-yaml) is now available.  You can install it from the testing repo.  Please try it out and share your feedback.

**Comment by fregster** [comment]
I've updated 4 servers now and ran against different configuration files all working for me. My unit testing is working but I do not have extreme edge case tests against my YAML file. My only issue was that I had compiled YAML and forgot to remove the config file created by phpize etc (A quick rm /etc/php.d/25-pecl-yaml-custom.ini and restart sorted it).

For me and from my testing this is STABLE

**Comment by carlwgeorge** [comment]
Thanks for the feedback @fregster.  I've promoted this package to the stable repo.
