### ISSUE TITLE
 php73-pecl-mongodb

### ISSUE THREAD

**Issue by andreagrax** [iusrepo/wishlist#240]
### What new package do you want?
 php73-pecl-mongodb

### Why?

php72u-pecl-mongodb.x86_64 0:1.4.2-1.ius.el7 is the latest version available on the repo , but we're planning to upgrade to php 7.3
### Testing

I agree to test the new package to ensure that it works as expected.  Once I am
satisfied with the results of my testing I will comment on this issue with the
word "STABLE" to get it promoted to the stable repos.

**Comment by rocket8899** [comment]
7.3

**Comment by carlwgeorge** [comment]
I've created [php73-pecl-mongodb](https://github.com/iusrepo/php73-pecl-mongodb) and published it to ius-testing.  Please try it out and share your feedback here.

**Comment by carlwgeorge** [comment]
@andreagrax How is this package working for you?

**Comment by mastertheknife** [comment]
I also need this package.
I will test next week and reply back.

**Comment by carlwgeorge** [comment]
Any word on testing @mastertheknife?

**Comment by mastertheknife** [comment]
I have a big application that uses this extension (along with mongodb-php library)
So far its all working well without issues.

**Comment by carlwgeorge** [comment]
Thanks for the confirmation @mastertheknife.  I've promoted this package to the stable repo.

**Comment by mastertheknife** [comment]
Hi,
For a recent project i needed mongodb extension version 1.6.0 (or newer), because of the transaction features.
I upgraded to php73-pecl-mongodb 1.6.0 from the testings repository and can confirm its working fine as intended. You can move that version to stable.

**Comment by carlwgeorge** [comment]
Thanks for the confirmation @mastertheknife.

I do want to point out that this issue was just for the initial package creation.  Feedback for future updates should be reported in other issues or pull requests, such as https://github.com/iusrepo/php73-pecl-mongodb/issues/1.

**Comment by mastertheknife** [comment]
@carlwgeorge 

Ok, got it, thank you!
