### ISSUE TITLE
php70u-pecl-ssh2

### ISSUE THREAD

**Issue by FancyFane** [iusrepo/wishlist#88]
### What package do you want?

php70u-pecl-ssh2.x86_64
### Why?

This will allow for a Wordpress installation where vsftpd is done through ssh keys, instead of passwords which is far more secure. 

Source: https://www.digitalocean.com/community/tutorials/how-to-configure-secure-updates-and-installations-in-wordpress-on-ubuntu

Further you're already packaging this file for php56u it would make sense to also offer it on php70:

```
[root@web01 ~]# yum info php56u-pecl-ssh2
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: repos.dfw.quadranet.com
 * epel: fedora-epel.mirror.lstn.net
 * extras: repos.dfw.quadranet.com
 * ius: dfw.mirror.rackspace.com
 * updates: repos.dfw.quadranet.com
Available Packages
Name        : php56u-pecl-ssh2
Arch        : x86_64
Version     : 0.13
Release     : 2.ius.centos7
Size        : 36 k
Repo        : ius/x86_64
Summary     : Bindings for the libssh2 library
URL         : http://pecl.php.net/package/ssh2
License     : PHP
Description : Bindings to the functions of libssh2 which implements the SSH2 protocol.
            : libssh2 is available from http://www.sourceforge.net/projects/libssh2
```
### OS versions

I would like this package for both RHEL/CenOS 6 and 7.
### Testing

I agree to test the new package on CentOS 7 cloud server.

**Comment by carlwgeorge** [comment]
Howdy @FancyFane,

Unfortunately, the ssh2 module does not have a PHP7-compatible stable release yet.  The upstream [README.md](https://github.com/php/pecl-networking-ssh2/blob/master/README.md) even includes this warning:

> The extension in the master branch is not in a state you should deploy on a production server.

Once it does we will revisit this request.

**Comment by FancyFane** [comment]
Thank you for the quick response. I'll keep an eye on this. It is not for a production system, just a development box. For now I'll downgrade to php56u which offers this package and wait for upstream. When it is released I'll be available for testing this package on php70u.

**Comment by b-harper** [comment]
I was check in on some stale issue.  There has been some [version bumps][0] to this module, but the warning is still on the [README.md][1].  At this point, I am not sure there will ever be a stable release.

[0]: https://github.com/php/pecl-networking-ssh2/commits/631e51c10001f01ce116080df028243a19e5f018/package.xml
[1]: https://github.com/php/pecl-networking-ssh2/blob/aa1739ac26c2177d33ab8d064021032bdc2c3a40/README.md

**Comment by carlwgeorge** [comment]
PHP 7.0 is end of life.
