### ISSUE TITLE
varnish-modules

### ISSUE THREAD

**Issue by gboddin** [iusrepo/wishlist#99]
### What package do you want?

varnish-modules 0.10

### Why?

https://github.com/gboddin/edge-repo-dev/blob/master/SPECS/varnish-modules.spec ( they have it upstream ) is already done, I was wondering if we could merge edge-repo and get rid of it.

### OS versions

I would like (to maintain) this package for both RHEL 6 and 7.

### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by carlwgeorge** [comment]
Howdy @gboddin,

Thanks for opening this request with us.  I have a few points of observation I wanted to write down and get your feedback on.

* IUS normally provides newer versions of stock packages.  varnish-modules is not available in the stock RHEL repos or EPEL (or Fedora).  If the same varnish-modules can be used with both varnish 4 and varnish 5, then the best course of action would be to get it added to EPEL (and Fedora).  In fact, it looks like that process was started some time ago, but never completed.  It exists in [pkgdb](https://admin.fedoraproject.org/pkgdb/package/rpms/varnish-modules/) and the [git repository](http://pkgs.fedoraproject.org/cgit/rpms/varnish-modules.git/) has been created, but there is no spec file and no builds in [koji](http://koji.fedoraproject.org/koji/packageinfo?packageID=23111).  Would you be willing to contact the [Fedora maintainer](https://admin.fedoraproject.org/pkgdb/packager/ingvar/) to see what the hold up is?

* Your spec file claims it's version 0.10.0, but downloads a tarball of a specific upstream commit.  In that commit, the [configure.ac file](https://github.com/varnish/varnish-modules/blob/daa4f1da5e34b274ca533766c5730696b1db7ca7/configure.ac#L3) states the version is still 0.9.1.  Additionally, the most recent release I can find is also [0.9.1](https://github.com/varnish/varnish-modules/releases/tag/varnish-modules-0.9.1).  Where did you get version 0.10.0 from?

**Comment by gboddin** [comment]
* Actually the last changes in the vmods cannot be used with the 4.0 version ("This release is intended to work with Varnish Cache 4.1.3 and higher." from https://github.com/varnish/varnish-modules/blob/master/CHANGES.rst)

* Yes it's in this file as well ( https://github.com/varnish/varnish-modules/blob/master/CHANGES.rst ), marked as unreleased, the commit mentionned in the spec file was the master at the time it was made. I was planning to release a new dist everytime this file gets updated.

**Comment by carlwgeorge** [comment]
For EL7, since this isn't in base or EPEL, it should be added to EPEL and is out of scope for IUS.  If the latest version of varnish-modules is not compatible with the current varnish 4.0.5 in EPEL, then there are two options:

1. Select an older, compatible version for the EPEL package.
2. Update the EPEL varnish package to a newer version.

If 2 is the best choice, the Fedora/EPEL maintainer may have to follow the [EPEL incompatible upgrades policy](https://fedoraproject.org/wiki/EPEL_incompatible_upgrades_policy) in order to get the EPEL package to a newer version.  This may make the most sense since varnish 4.x is EOL upstream.

**Comment by carlwgeorge** [comment]
For what it's worth, EL8 is out now and includes varnish 6.0.2 and varnish-modules 0.15.0.
